add `using namespace utils` to resolve `doubleAlign`
old version causes error
```
fftw++.h:92:20: error: ‘doubleAlign’ is not a member of ‘fftwpp’; did you mean ‘utils::doubleAlign’?
   92 | #define FFTWdouble doubleAlign
      |                    ^~~~~~~~~~~
```
`#define FFTWdouble utils::doubleAlign` is not possible
(throws `error: ‘fftwpp::utils’ has not been declared`)
so we use `using namespace utils;`